// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Rewire = require("../src/Rewire.bs.js");

var testAssetLocation = "../../../__tests__/assets/testAsset.js";

var include = Rewire.MakeRewired(/* module */[]);

var TestAssetModule_000 = /* set */include[0];

var TestAssetModule_001 = /* setAll */include[1];

var TestAssetModule_002 = /* get */include[2];

var TestAssetModule_003 = /* withRewiring */include[3];

var TestAssetModule_004 = /* withRewiringOver */include[4];

var TestAssetModule_005 = /* withAsyncRewiring */include[5];

var TestAssetModule_006 = /* withAsyncRewiringOver */include[6];

var TestAssetModule = /* module */[
  TestAssetModule_000,
  TestAssetModule_001,
  TestAssetModule_002,
  TestAssetModule_003,
  TestAssetModule_004,
  TestAssetModule_005,
  TestAssetModule_006
];

var include$1 = Rewire.MakeModuleRewiring([]);

var rewire = include$1[0];

var TestAssetRewirting = /* module */[/* rewire */rewire];

describe("Rewire", (function () {
        return Jest.test("MakeRewired & MakeModuleRewiring can be used to define custom module APIs", (function () {
                      var rewiredModule = Curry._1(rewire, testAssetLocation);
                      return Jest.Expect[/* toEqual */12]("someValue", Jest.Expect[/* expect */0](rewiredModule.getParam()));
                    }));
      }));

exports.testAssetLocation = testAssetLocation;
exports.TestAssetModule = TestAssetModule;
exports.TestAssetRewirting = TestAssetRewirting;
/* include Not a pure module */
