// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Rewire = require("rewire");

var getParam = (
        function(rewiredModule) {
          return rewiredModule.getParam();
        }
      );

var getOtherParam = (
      function(rewiredModule) {
        return rewiredModule.getOtherParam();
      }
    );

function oneParamModuleToJs(param) {
  return {
          param: param[/* param */0]
        };
}

function oneParamModuleFromJs(param) {
  return /* record */[/* param */param.param];
}

describe("Rewire", (function () {
        Jest.test("rewire requires a module", (function () {
                var rewiredModule = Rewire("./testAsset.js");
                return Jest.Expect[/* toEqual */12]("someValue", Jest.Expect[/* expect */0](Curry._1(getParam, rewiredModule)));
              }));
        Jest.test("rewire.get gets a named value in a module", (function () {
                var rewiredModule = Rewire("./testAsset.js");
                return Jest.Expect[/* toEqual */12]({
                            param: /* param */"someValue"
                          }, Jest.Expect[/* expect */0](rewiredModule.__get__("someModule")));
              }));
        Jest.test("rewire.set sets a value in a module", (function () {
                var rewiredModule = Rewire("./testAsset.js");
                Jest.Expect[/* toEqual */12]("someValue", Jest.Expect[/* expect */0](Curry._1(getParam, rewiredModule)));
                rewiredModule.__set__("someModule", {
                      param: /* param */"someMockedValue"
                    });
                return Jest.Expect[/* toEqual */12]("someMockedValue", Jest.Expect[/* expect */0](Curry._1(getParam, rewiredModule)));
              }));
        Jest.test("rewire.setAll sets multiple values in a module", (function () {
                var all = { };
                all["someModule"] = {
                  param: /* param */"someMockedValue"
                };
                all["someOtherModule"] = {
                  param: /* param */"someOtherMockedValue"
                };
                var rewiredModule = Rewire("./testAsset.js");
                rewiredModule.__set__(all);
                Jest.Expect[/* toEqual */12]("someMockedValue", Jest.Expect[/* expect */0](Curry._1(getParam, rewiredModule)));
                return Jest.Expect[/* toEqual */12]("someOtherMockedValue", Jest.Expect[/* expect */0](Curry._1(getOtherParam, rewiredModule)));
              }));
        Jest.testAsync(/* None */0, "rewire.withRewiring takes a callback in which values are mocked", (function (finish) {
                var rewiredModule = Rewire("./testAsset.js");
                var all = { };
                all["someModule"] = {
                  param: /* param */"someMockedValue"
                };
                var rewiringCallback = rewiredModule.__with__(all);
                return Curry._1(rewiringCallback, (function () {
                              return Curry._1(finish, Jest.Expect[/* toEqual */12]("someMockedValue", Jest.Expect[/* expect */0](Curry._1(getParam, rewiredModule))));
                            }));
              }));
        return Jest.testAsync(/* None */0, "rewire.withAsyncRewiring take a promised callback which resolves with variables reset to their original value", (function (finish) {
                      var rewiredModule = Rewire("./testAsset.js");
                      var all = { };
                      all["someModule"] = {
                        param: /* param */"someMockedValue"
                      };
                      var rewiringCallback = rewiredModule.__with__(all);
                      Curry._1(rewiringCallback, (function () {
                                return Promise.resolve(/* () */0);
                              })).then((function () {
                              return Promise.resolve(Curry._1(finish, Jest.Expect[/* toEqual */12]("someValue", Jest.Expect[/* expect */0](Curry._1(getParam, rewiredModule)))));
                            }));
                      return /* () */0;
                    }));
      }));

exports.getParam = getParam;
exports.getOtherParam = getOtherParam;
exports.oneParamModuleToJs = oneParamModuleToJs;
exports.oneParamModuleFromJs = oneParamModuleFromJs;
/* getParam Not a pure module */
